name: pf_service
description: Premium Filter API Service
version: 0.0.4
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  retry: ^3.1.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter